steps: 
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - build
    - --file=./Dockerfile
    - -t
    - gcr.io/kubernetes-history-inspector/standalone:${_IMAGE_TAG}
    - -t
    - gcr.io/kubernetes-history-inspector/standalone:latest
    - .
    waitFor: ["-"]
images:
  - gcr.io/kubernetes-history-inspector/standalone:${_IMAGE_TAG}
  - gcr.io/kubernetes-history-inspector/standalone:latest