FROM golang:1.25 as builder

ENV ROOT=/go/src/app
RUN mkdir /built
WORKDIR ${ROOT}
RUN apt update
COPY go.mod go.sum ./
RUN go mod download

COPY . ${ROOT}
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /built/analytics cmd/analytics/main.go
RUN mkdir /built/data

FROM scratch
ENV ROOT=/go/src/app
WORKDIR ${ROOT}
COPY --from=builder /built/analytics ${ROOT}
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

CMD ["/go/src/app/analytics"]
