// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by scripts/backend-codegen. DO NOT EDIT.

package generated

import (
	"fmt"

	coreinspection "github.com/GoogleCloudPlatform/khi/pkg/core/inspection"
{{- range .}}
	{{.ImplPackageName}} "{{.ImplPackageImportPath}}"
{{- end}}
)

// RegisterAllInspectionTasks register all inspection tasks defined in this repository into the given inspection server.
// DO NOT EDIT. This code is generated by backend-codegen.
func RegisterAllInspectionTasks(inspectionServer *coreinspection.InspectionTaskServer) error {
	var err error
{{- range .}}
	err = {{.ImplPackageName}}.Register(inspectionServer)
	if err != nil {
		return fmt.Errorf("failed to register package {{.PackageNamePrefix}} (at {{.PackageImportPathBase}})\nError:%s", err.Error())
	} 
{{- end}}
	return nil
}
