// Code generated by scripts/backend-codegen. DO NOT EDIT.

package {{.PackageName}}

// This import is necessary for testing on CI environment to supply test flags because each test packages are built as independent binary.
import (
	_ "github.com/GoogleCloudPlatform/khi/internal/testflags"
)
