// This file is generated by scripts/frontend-codegen; DO NOT EDIT.

// Parent relationship

/**
 * ParentRelationship type represents how the timeline relates its parent timeline.
 */
export enum ParentRelationship {
  RelationshipChild = 0,
  RelationshipResourceStatus = 1,
  RelationshipOperation = 2,
  RelationshipEndpointSlice = 3,
  RelationshipContainer = 4,
  RelationshipNodeComponent = 5,
  RelationshipOwnerReference = 6,
  RelationshipPodBinding = 7,
  RelationshipNetworkEndpointGroup = 8,
  RelationshipManagedInstanceGroup = 9,

  Unknown = -1,
}

export interface ParentRelationshipMetadataType {
  visible: boolean;
  label: string;
  hint: string;
}

export const ParentRelationshipMetadata: ParentRelationshipMetadataType[] = [
  {
    visible: false,
    label: '',
    hint: '',
  },

  {
    visible: true,
    label: 'status',
    hint: 'Resource status written on .status.conditions',
  },

  {
    visible: true,
    label: 'operation',
    hint: 'GCP operations associated with this resource',
  },

  {
    visible: true,
    label: 'endpointslice',
    hint: 'Pod serving status obtained from endpoint slice',
  },

  {
    visible: true,
    label: 'container',
    hint: 'Containers statuses/logs in Pods',
  },

  {
    visible: true,
    label: 'node-component',
    hint: 'Non container resource running on a node',
  },

  {
    visible: true,
    label: 'owns',
    hint: 'A k8s resource related to this resource from .metadata.ownerReference field',
  },

  {
    visible: true,
    label: 'binds',
    hint: 'Pod binding subresource associated with this node',
  },

  {
    visible: true,
    label: 'neg',
    hint: 'Pod serving status obtained from the associated NEG status',
  },

  {
    visible: true,
    label: 'mig',
    hint: 'MIG logs associated to the parent node pool',
  },
];

export function ParentRelationshipToLabel(rel: ParentRelationship): string {
  return ParentRelationshipMetadata[rel].label;
}

export function ParseParentRelationshipLabel(
  label: string,
): ParentRelationship {
  switch (label) {
    case '':
      return ParentRelationship.RelationshipChild;
    case 'status':
      return ParentRelationship.RelationshipResourceStatus;
    case 'operation':
      return ParentRelationship.RelationshipOperation;
    case 'endpointslice':
      return ParentRelationship.RelationshipEndpointSlice;
    case 'container':
      return ParentRelationship.RelationshipContainer;
    case 'node-component':
      return ParentRelationship.RelationshipNodeComponent;
    case 'owns':
      return ParentRelationship.RelationshipOwnerReference;
    case 'binds':
      return ParentRelationship.RelationshipPodBinding;
    case 'neg':
      return ParentRelationship.RelationshipNetworkEndpointGroup;
    case 'mig':
      return ParentRelationship.RelationshipManagedInstanceGroup;
    default:
      return ParentRelationship.Unknown;
  }
}

export enum RevisionVerb {
  RevisionVerbUnknown = 0,
  RevisionVerbCreate = 1,
  RevisionVerbDelete = 2,
  RevisionVerbUpdate = 3,
  RevisionVerbPatch = 4,
  RevisionVerbDeleteCollection = 5,
  RevisionVerbReady = 6,
  RevisionVerbNonReady = 7,
  RevisionVerbOperationStart = 8,
  RevisionVerbOperationFinish = 9,
  RevisionVerbStatusUnknown = 10,
  RevisionVerbStatusTrue = 11,
  RevisionVerbStatusFalse = 12,
  RevisionVerbContainerWaiting = 13,
  RevisionVerbContainerReady = 14,
  RevisionVerbContainerNonReady = 15,
  RevisionVerbContainerSuccess = 16,
  RevisionVerbContainerError = 17,
  RevisionVerbComposerTaskInstanceScheduled = 18,
  RevisionVerbComposerTaskInstanceQueued = 19,
  RevisionVerbComposerTaskInstanceRunning = 20,
  RevisionVerbComposerTaskInstanceUpForRetry = 21,
  RevisionVerbComposerTaskInstanceSuccess = 22,
  RevisionVerbComposerTaskInstanceFailed = 23,
  RevisionVerbComposerTaskInstanceDeferred = 24,
  RevisionVerbComposerTaskInstanceUpForReschedule = 25,
  RevisionVerbComposerTaskInstanceRemoved = 26,
  RevisionVerbComposerTaskInstanceUpstreamFailed = 27,
  RevisionVerbComposerTaskInstanceZombie = 28,
  RevisionVerbComposerTaskInstanceStats = 29,
  RevisionVerbComposerTaskInstanceUnimplemented = 30,
  RevisionVerbTerminating = 31,
}

export interface RevisionVerbMetadataType {
  label: string;
  selector: string;
}

export const RevisionVerbMetadata: RevisionVerbMetadataType[] = [
  {
    label: 'Unknown',
    selector: 'unknown',
  },
  {
    label: 'Create',
    selector: 'create',
  },
  {
    label: 'Delete',
    selector: 'delete',
  },
  {
    label: 'Update',
    selector: 'update',
  },
  {
    label: 'Patch',
    selector: 'patch',
  },
  {
    label: 'DeleteCollection',
    selector: 'delete-collection',
  },
  {
    label: 'Ready',
    selector: 'ready',
  },
  {
    label: 'NonReady',
    selector: 'non-ready',
  },
  {
    label: 'Start',
    selector: 'operation-start',
  },
  {
    label: 'Finish',
    selector: 'operation-finish',
  },
  {
    label: 'Condition(Unknown)',
    selector: 'status-unknown',
  },
  {
    label: 'Condition(True)',
    selector: 'status-true',
  },
  {
    label: 'Condition(False)',
    selector: 'status-false',
  },
  {
    label: 'Waiting',
    selector: 'container-waiting',
  },
  {
    label: 'Ready',
    selector: 'container-ready',
  },
  {
    label: 'NonReady',
    selector: 'container-non-ready',
  },
  {
    label: 'Success',
    selector: 'container-success',
  },
  {
    label: 'Error',
    selector: 'container-error',
  },
  {
    label: 'Scheduled',
    selector: 'composer-taskinstance-scheduled',
  },
  {
    label: 'Queued',
    selector: 'composer-taskinstance-queued',
  },
  {
    label: 'Running',
    selector: 'composer-taskinstance-running',
  },
  {
    label: 'UpForRetry',
    selector: 'composer-taskinstance-upforretry',
  },
  {
    label: 'Success',
    selector: 'composer-taskinstance-success',
  },
  {
    label: 'Failed',
    selector: 'composer-taskinstance-failed',
  },
  {
    label: 'Deferred',
    selector: 'composer-taskinstance-deferred',
  },
  {
    label: 'UpForReschedule',
    selector: 'composer-taskinstance-upforreschedule',
  },
  {
    label: 'Removed',
    selector: 'composer-taskinstance-removed',
  },
  {
    label: 'UpstreamFailed',
    selector: 'composer-taskinstance-upstreamfailed',
  },
  {
    label: 'Zombie',
    selector: 'composer-taskinstance-zombie',
  },
  {
    label: 'Stats',
    selector: 'composer-taskinstance-stats',
  },
  {
    label: 'Unimplemented',
    selector: 'composer-taskinstance-unimplemented',
  },
  {
    label: 'Terminating',
    selector: 'terminating',
  },
];

// log types
export enum LogType {
  LogTypeUnknown = 0,
  LogTypeEvent = 1,
  LogTypeAudit = 2,
  LogTypeContainer = 3,
  LogTypeNode = 4,
  LogTypeGkeAudit = 5,
  LogTypeComputeApi = 6,
  LogTypeMulticloudAPI = 7,
  LogTypeOnPremAPI = 8,
  LogTypeNetworkAPI = 9,
  LogTypeAutoscaler = 10,
  LogTypeComposerEnvironment = 11,
  LogTypeControlPlaneComponent = 12,
}

export interface LogTypeMetadataType {
  label: string;
}

export const LogTypeMetadata: LogTypeMetadataType[] = [
  {
    label: 'unknown',
  },
  {
    label: 'k8s_event',
  },
  {
    label: 'k8s_audit',
  },
  {
    label: 'k8s_container',
  },
  {
    label: 'k8s_node',
  },
  {
    label: 'gke_audit',
  },
  {
    label: 'compute_api',
  },
  {
    label: 'multicloud_api',
  },
  {
    label: 'onprem_api',
  },
  {
    label: 'network_api',
  },
  {
    label: 'autoscaler',
  },
  {
    label: 'composer_environment',
  },
  {
    label: 'control_plane_component',
  },
];

export const logTypes = [
  'unknown',
  'k8s_event',
  'k8s_audit',
  'k8s_container',
  'k8s_node',
  'gke_audit',
  'compute_api',
  'multicloud_api',
  'onprem_api',
  'network_api',
  'autoscaler',
  'composer_environment',
  'control_plane_component',
];

export const logTypeColors: { [logType: string]: string } = {
  unknown: '#000000',
  k8s_event: '#3fb549',
  k8s_audit: '#000000',
  k8s_container: '#fe9bab',
  k8s_node: '#0077CC',
  gke_audit: '#AA00FF',
  compute_api: '#FFCC33',
  multicloud_api: '#AA00FF',
  onprem_api: '#AA00FF',
  network_api: '#33CCFF',
  autoscaler: '#FF5555',
  composer_environment: '#88AA55',
  control_plane_component: '#FF3333',
};

export const logTypeDarkColors: { [logType: string]: string } = {
  autoscaler: 'hsl(0.000000deg 100.000000% 53.360000%)',
  composer_environment: 'hsl(84.000000deg 33.300000% 40.000000%)',
  compute_api: 'hsl(45.000000deg 100.000000% 48.000000%)',
  control_plane_component: 'hsl(0.000000deg 100.000000% 48.000000%)',
  gke_audit: 'hsl(280.000000deg 100.000000% 40.000000%)',
  k8s_audit: 'hsl(0.000000deg 0.000000% 80.000000%)',
  k8s_container: 'hsl(350.303030deg 98.000000% 64.160000%)',
  k8s_event: 'hsl(125.084746deg 48.400000% 38.240000%)',
  k8s_node: 'hsl(205.000000deg 100.000000% 32.000000%)',
  multicloud_api: 'hsl(280.000000deg 100.000000% 40.000000%)',
  network_api: 'hsl(195.000000deg 100.000000% 48.000000%)',
  onprem_api: 'hsl(280.000000deg 100.000000% 40.000000%)',
  unknown: 'hsl(0.000000deg 0.000000% 80.000000%)',
};

export enum RevisionState {
  RevisionStateInferred = 0,
  RevisionStateExisting = 1,
  RevisionStateDeleted = 2,
  RevisionStateConditionTrue = 3,
  RevisionStateConditionFalse = 4,
  RevisionStateConditionUnknown = 5,
  RevisionStateOperationStarted = 6,
  RevisionStateOperationFinished = 7,
  RevisionStateContainerWaiting = 8,
  RevisionStateContainerRunningNonReady = 9,
  RevisionStateContainerRunningReady = 10,
  RevisionStateContainerTerminatedWithSuccess = 11,
  RevisionStateContainerTerminatedWithError = 12,
  RevisionStateComposerTiScheduled = 13,
  RevisionStateComposerTiQueued = 14,
  RevisionStateComposerTiRunning = 15,
  RevisionStateComposerTiDeferred = 16,
  RevisionStateComposerTiSuccess = 17,
  RevisionStateComposerTiFailed = 18,
  RevisionStateComposerTiUpForRetry = 19,
  RevisionStateComposerTiRestarting = 20,
  RevisionStateComposerTiRemoved = 21,
  RevisionStateComposerTiUpstreamFailed = 22,
  RevisionStateComposerTiZombie = 23,
  RevisionStateComposerTiUpForReschedule = 24,
  RevisionStateDeleting = 25,
  RevisionStateEndpointReady = 26,
  RevisionStateEndpointTerminating = 27,
  RevisionStateEndpointUnready = 28,
}

export interface RevisionStateMetadataType {
  cssSelector: string;
  label: string;
}

export const RevisionStateMetadata: RevisionStateMetadataType[] = [
  {
    cssSelector: 'inferred',
    label: 'Resource may be existing',
  },

  {
    cssSelector: 'existing',
    label: 'Resource is existing',
  },

  {
    cssSelector: 'deleted',
    label: 'Resource is deleted',
  },

  {
    cssSelector: 'condition_true',
    label: "State is 'True'",
  },

  {
    cssSelector: 'condition_false',
    label: "State is 'False'",
  },

  {
    cssSelector: 'condition_unknown',
    label: "State is 'Unknown'",
  },

  {
    cssSelector: 'operation_started',
    label: 'Processing operation',
  },

  {
    cssSelector: 'operation_finished',
    label: 'Operation is finished',
  },

  {
    cssSelector: 'container_waiting',
    label: 'Waiting for starting container',
  },

  {
    cssSelector: 'container_running_non_ready',
    label: 'Container is not ready',
  },

  {
    cssSelector: 'container_running_ready',
    label: 'Container is ready',
  },

  {
    cssSelector: 'container_terminated_success',
    label: 'Container exited with healthy exit code',
  },

  {
    cssSelector: 'container_terminated_error',
    label: 'Container exited with errornous exit code',
  },

  {
    cssSelector: 'composer_ti_scheduled',
    label: 'Task instance is scheduled',
  },

  {
    cssSelector: 'composer_ti_queued',
    label: 'Task instance is queued',
  },

  {
    cssSelector: 'composer_ti_running',
    label: 'Task instance is running',
  },

  {
    cssSelector: 'composer_ti_deferred',
    label: 'Task instance is deferrd',
  },

  {
    cssSelector: 'composer_ti_success',
    label: 'Task instance completed with success state',
  },

  {
    cssSelector: 'composer_ti_failed',
    label: 'Task instance completed with errournous state',
  },

  {
    cssSelector: 'composer_ti_up_for_retry',
    label: 'Task instance is waiting for next retry',
  },

  {
    cssSelector: 'composer_ti_restarting',
    label: 'Task instance is being restarted',
  },

  {
    cssSelector: 'composer_ti_removed',
    label: 'Task instance is removed',
  },

  {
    cssSelector: 'composer_ti_upstream_failed',
    label: 'Upstream of this task is failed',
  },

  {
    cssSelector: 'composer_ti_zombie',
    label: 'Task instance is being zombie',
  },

  {
    cssSelector: 'composer_ti_up_for_reschedule',
    label: 'Task instance is waiting for being rescheduled',
  },

  {
    cssSelector: 'deleting',
    label: 'Resource is under deleting with graceful period',
  },

  {
    cssSelector: 'ready',
    label: 'Endpoint is ready',
  },

  {
    cssSelector: 'terminating',
    label: 'Endpoint is being terminated',
  },

  {
    cssSelector: 'unready',
    label: 'Endpoint is not ready',
  },
];

export const revisionStates = [
  'inferred',
  'existing',
  'deleted',
  'condition_true',
  'condition_false',
  'condition_unknown',
  'operation_started',
  'operation_finished',
  'container_waiting',
  'container_running_non_ready',
  'container_running_ready',
  'container_terminated_success',
  'container_terminated_error',
  'composer_ti_scheduled',
  'composer_ti_queued',
  'composer_ti_running',
  'composer_ti_deferred',
  'composer_ti_success',
  'composer_ti_failed',
  'composer_ti_up_for_retry',
  'composer_ti_restarting',
  'composer_ti_removed',
  'composer_ti_upstream_failed',
  'composer_ti_zombie',
  'composer_ti_up_for_reschedule',
  'deleting',
  'ready',
  'terminating',
  'unready',
];

export const revisionStatecolors: { [state: string]: string } = {
  inferred: '#997700',
  existing: '#0000FF',
  deleted: '#CC0000',
  condition_true: '#004400',
  condition_false: '#EE4400',
  condition_unknown: '#663366',
  operation_started: '#004400',
  operation_finished: '#333333',
  container_waiting: '#997700',
  container_running_non_ready: '#EE4400',
  container_running_ready: '#007700',
  container_terminated_success: '#113333',
  container_terminated_error: '#331111',
  composer_ti_scheduled: '#d1b48c',
  composer_ti_queued: '#808080',
  composer_ti_running: '#00ff01',
  composer_ti_deferred: '#9470dc',
  composer_ti_success: '#008001',
  composer_ti_failed: '#fe0000',
  composer_ti_up_for_retry: '#fed700',
  composer_ti_restarting: '#ee82ef',
  composer_ti_removed: '#d3d3d3',
  composer_ti_upstream_failed: '#ffa11b',
  composer_ti_zombie: '#696969',
  composer_ti_up_for_reschedule: '#808080',
  deleting: '#CC5500',
  ready: '#004400',
  terminating: '#fed700',
  unready: '#EE4400',
};

export const revisionStateDarkColors: { [state: string]: string } = {
  composer_ti_deferred: 'hsl(260.000000deg 60.700000% 52.080000%)',
  composer_ti_failed: 'hsl(0.000000deg 100.000000% 39.840000%)',
  composer_ti_queued: 'hsl(0.000000deg 0.000000% 40.160000%)',
  composer_ti_removed: 'hsl(0.000000deg 0.000000% 66.160000%)',
  composer_ti_restarting: 'hsl(299.449541deg 77.300000% 57.920000%)',
  composer_ti_running: 'hsl(120.235294deg 100.000000% 40.000000%)',
  composer_ti_scheduled: 'hsl(34.782609deg 42.900000% 54.720000%)',
  composer_ti_success: 'hsl(120.468750deg 100.000000% 20.080000%)',
  composer_ti_up_for_reschedule: 'hsl(0.000000deg 0.000000% 40.160000%)',
  composer_ti_up_for_retry: 'hsl(50.787402deg 100.000000% 39.840000%)',
  composer_ti_upstream_failed: 'hsl(35.263158deg 100.000000% 44.240000%)',
  composer_ti_zombie: 'hsl(0.000000deg 0.000000% 32.960000%)',
  condition_false: 'hsl(17.142857deg 100.000000% 37.360000%)',
  condition_true: 'hsl(120.000000deg 100.000000% 10.640000%)',
  condition_unknown: 'hsl(300.000000deg 33.300000% 24.000000%)',
  container_running_non_ready: 'hsl(17.142857deg 100.000000% 37.360000%)',
  container_running_ready: 'hsl(120.000000deg 100.000000% 18.640000%)',
  container_terminated_error: 'hsl(0.000000deg 50.000000% 10.640000%)',
  container_terminated_success: 'hsl(180.000000deg 50.000000% 10.640000%)',
  container_waiting: 'hsl(46.666667deg 100.000000% 24.000000%)',
  deleted: 'hsl(0.000000deg 100.000000% 32.000000%)',
  deleting: 'hsl(25.000000deg 100.000000% 32.000000%)',
  existing: 'hsl(240.000000deg 100.000000% 40.000000%)',
  inferred: 'hsl(46.666667deg 100.000000% 24.000000%)',
  operation_finished: 'hsl(0.000000deg 0.000000% 16.000000%)',
  operation_started: 'hsl(120.000000deg 100.000000% 10.640000%)',
  ready: 'hsl(120.000000deg 100.000000% 10.640000%)',
  terminating: 'hsl(50.787402deg 100.000000% 39.840000%)',
  unready: 'hsl(17.142857deg 100.000000% 37.360000%)',
};

export const revisionStateToIndex: { [state: string]: number } = {};
for (let i = 0; i < revisionStates.length; i++) {
  revisionStateToIndex[revisionStates[i]] = i;
}

// severities

/**
 * Severity represents severity of a log.
 */
export enum Severity {
  SeverityUnknown = 0,
  SeverityInfo = 1,
  SeverityWarning = 2,
  SeverityError = 3,
  SeverityFatal = 4,
}

export interface SeverityMetadataType {
  label: string;
}

export const SeverityMetadata: SeverityMetadataType[] = [
  {
    label: 'UNKNOWN',
  },
  {
    label: 'INFO',
  },
  {
    label: 'WARNING',
  },
  {
    label: 'ERROR',
  },
  {
    label: 'FATAL',
  },
];

export const severities = ['UNKNOWN', 'INFO', 'WARNING', 'ERROR', 'FATAL'];

export const severityColors: { [state: string]: string } = {
  UNKNOWN: '#000000',
  INFO: '#0000FF',
  WARNING: '#FFAA44',
  ERROR: '#FF3935',
  FATAL: '#AA66AA',
};

export const severityBorderColors: { [state: string]: string } = {
  UNKNOWN: '#AAAAAA',
  INFO: '#1E88E5',
  WARNING: '#FDD835',
  ERROR: '#FF8888',
  FATAL: '#FF99FF',
};

export const severityToIndex: { [state: string]: number } = {};
for (let i = 0; i < severities.length; i++) {
  severityToIndex[severities[i]] = i;
}
