# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: get gcloud token
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud auth print-access-token >> ./.token
  - id: test go
    name: golang:1.24
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo "#!/bin/bash\necho \"`cat ./.token`\"" > /usr/bin/gcloud
        chmod +x /usr/bin/gcloud
        mkdir dist
        # A placeholder frontend code read from backend test
        echo "<!--INJECT GENERATED CODE HERE FROM BACKEND-->" > ./dist/index.html
        GCP_ACCESS_TOKEN=`cat ./.token` make coverage-go
        test_exit_code=$?
        rm ./.token
        exit "$test_exit_code"
    waitFor:
      - "get gcloud token"
  - name: golang:1.24
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make check-format-go
        make lint-go
    waitFor:
      - "-"
artifacts:
  objects:
    location: 'gs://kubernetes-history-inspector_cloudbuild/artifacts/$COMMIT_SHA'
    paths:
      - go-cover.html
options:
  machineType: E2_HIGHCPU_32