# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: npm install
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        cd ./web
        npm ci
    waitFor:
      - "-"
  - id: generate frontend codes
    name: golang:1.24
    entrypoint: /bin/bash
    args:
      - -c
      - |
        apt-get update && apt-get install jq -y
        make prepare-frontend
    waitFor:
      - npm install
  - id: angular test
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        wget -nv https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt-get -qq update > /dev/null && apt-get -qq install -y libappindicator1 fonts-liberation jq ./google-chrome-stable_current_amd64.deb > /dev/null
        make coverage-web
    waitFor:
      - generate frontend codes
  - id: upload coverage result
    name: "gcr.io/cloud-builders/gcloud-slim"
    args:
    - "storage"
    - "cp"
    - "--recursive"
    - "./web/coverage/frontend"
    - "gs://kubernetes-history-inspector_cloudbuild/artifacts/$COMMIT_SHA/frontend"
  - id: lint web
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make lint-web
    waitFor:
      - generate frontend codes
  - id: check format web
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make check-format-web
    waitFor:
      - generate frontend codes
  - id: build web internal
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        apt-get update && apt-get install jq -y
        cd web && cat angular.json | jq '.projects.frontend.architect.build.configurations|to_entries[]|.key' -r | xargs -I@ bash -c -x "npx ng build --configuration @"
options:
  machineType: E2_HIGHCPU_32
