# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: npm install
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        cd ./web
        npm ci
    waitFor:
      - "-"
  - id: backend-generate
    name: golang:1.25
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make generate-backend
  - id: generate frontend codes
    name: golang:1.25
    entrypoint: /bin/bash
    args:
      - -c
      - |
        apt-get update && apt-get install jq -y
        make prepare-frontend
    waitFor:
      - npm install
  - id: build web for internal version
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make build-web-internal-beta
    waitFor:
      - generate frontend codes
  - id: build test version container
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --file=./Dockerfile
      - -t
      - gcr.io/khi-internal/standalone:$COMMIT_SHA
      - .
    waitFor:
      - backend-generate
      - build web for internal version
  - id: build web for internal khi-ro version
    name: node:20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make build-web-internal-khi-ro
    waitFor:
      - backend-generate
      - build test version container # This overwrite the result from build web. Thus it can't be run parallel with building container
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        rm .gcloudignore
        mv ./scripts/private/khi-ro.gcloudignore .gcloudignore
        gcloud app deploy --project="google.com:khi-ro" --no-promote --version $COMMIT_SHA
    waitFor:
      - build web for internal khi-ro version
images:
  - gcr.io/khi-internal/standalone:$COMMIT_SHA
options:
  machineType: E2_HIGHCPU_32