# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _UPDATE_VERSION_FILE: "true"
  _MAKE_TARGET: "build-web-internal"
  _TAG: "latest"
  _TAG_SECOND_PREFIX: ""
  _KHI_RO_DEPLOY_FLAGS: "--version main"

steps:
  - id: install_deps
    name: "gcr.io/kubernetes-history-inspector/builder:latest"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        cd ./web
        npm ci
    waitFor:
      - "-"
  - id: build_app
    name: "gcr.io/kubernetes-history-inspector/builder:latest"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        if [ "${_UPDATE_VERSION_FILE}" = "true" ]; then
          echo "${_LOUHI_TAG_NAME}" > VERSION
        fi
        make ${_MAKE_TARGET}
    waitFor:
      - install_deps
  - id: build_container
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build --file=./Dockerfile -t gcr.io/khi-internal/standalone:${_TAG} -t gcr.io/khi-internal/standalone:${_TAG_SECOND_PREFIX}$(cat ./VERSION) .
        docker push gcr.io/khi-internal/standalone:${_TAG}
        docker push gcr.io/khi-internal/standalone:${_TAG_SECOND_PREFIX}$(cat ./VERSION)
    waitFor:
      - build_app
  - id: build web viewer mode
    name: "gcr.io/kubernetes-history-inspector/builder:latest"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make build-web-internal-khi-ro
    waitFor:
      - build_container # This overwrite the result from build web. Thus it can't be run parallel with building container
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        rm .gcloudignore
        mv ./scripts/private/khi-ro.gcloudignore .gcloudignore
        gcloud app deploy --project="google.com:khi-ro" ${_KHI_RO_DEPLOY_FLAGS}
    waitFor:
      - build web viewer mode
images:
  - gcr.io/khi-internal/standalone:${_TAG}
options:
  machineType: E2_HIGHCPU_32
