steps:
  - id: npm install
    name: node:18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        cd ./web
        npm ci
    waitFor:
      - "-"
  - id: build web beta
    name: node:18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make build-web-beta
    waitFor:
      - npm install
  - id: build beta container
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build --file=./Dockerfile -t gcr.io/kubernetes-history-inspector/standalone:beta -t gcr.io/kubernetes-history-inspector/standalone:beta-$(cat ./VERSION) .
        docker push gcr.io/kubernetes-history-inspector/standalone:beta
        docker push gcr.io/kubernetes-history-inspector/standalone:beta-$(cat ./VERSION)
    waitFor:
      - build web beta
  - id: build web viewer mode
    name: node:18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        NG_APP_GOOGLE_DRIVE_CLIENT_ID="173883494332-f5o6gkmpb5fku5u3vp43279mqbj24pe5.apps.googleusercontent.com" make build-web-viewer-mode
    waitFor:
      - build beta container # This overwrite the result from build web. Thus it can't be run parallel with building container
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud app deploy --project="google.com:khi-ro" --ignore-file=.gcloudignore-khi-ro --no-promote --version beta
    waitFor:
      - build web viewer mode
images:
  - gcr.io/kubernetes-history-inspector/standalone:beta
options:
  machineType: E2_HIGHCPU_32